version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue-tracker
    ports:
      - 5432:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
